---
name: A job to test the LIFX Build Light
on: [push]

jobs:
  test_lifx_job:
    runs-on: ubuntu-latest
    name: Run example
    steps:
    - name: Test build light Success
      uses: smarthall/lifx-buildlight-action@master
      with:
        lifx-token: ${{ secrets.LIFX_TOKEN }}
        selector: 'location:Work'
        status: 'success'
